### ISSUE TITLE
Cannot add more than one user

### ISSUE THREAD

**Issue by andreakb** [mjordan/islandora_rest_authen#6]
Hello, when we tried to to add another user to the configuration through the UI, none of the api key pairs worked. When we had one key pair in the configuration, it worked fine. When added the new key pair to the configuration in a new line, none of the key pairs worked. We tried on google chrome Version 68.0.3440.106 (Official Build) (64-bit) and Firefox 61.0.2 (64-bit). Thanks!

**Comment by mjordan** [comment]
OK, thanks for reporting this. I probably won't get to investigate it until the weekend however.

**Comment by mjordan** [comment]
Also, the Islandora REST module now comes with its own [submodule](https://github.com/discoverygarden/islandora_rest/tree/7.x/modules/islandora_rest_api_auth) that allows token-based authentication. You could try that option.

**Comment by mjordan** [comment]
@andreakb I've confirmed the issue, and am working on resolving it.

**Comment by mjordan** [comment]
@andreakb can you test the issue-6 branch and let me know if it resolves the issue?

**Comment by andreakb** [comment]
Yup, it resolves the issue. Thanks so much!

**Comment by mjordan** [comment]
Excellent, thanks for pointing that out. I've merged the update into the 7.x branch.
